# Generated by Django 4.2.1 on 2024-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_normaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.BooleanField(default=False),
        ),
    ]
