# Generated by Django 5.0.3 on 2024-03-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0002_credential_id_bytes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='transports',
        ),
        migrations.AddField(
            model_name='credential',
            name='transports_json',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
