# Generated by Django 5.0.3 on 2024-03-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0004_rename_transports_json_credential_transports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='transports',
            field=models.CharField(max_length=255),
        ),
    ]
