# Generated by Django 5.0.3 on 2024-03-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0006_temporarychallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='id_bytes',
        ),
    ]
